stages:
  - lint

before_script:
  - docker info
  - apk update && apk add git
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

services:
- docker:dind

lint-python:
  stage: lint
  except:
  - master
  script:
  - |
    BASE=$(git merge-base origin/master $CI_BUILD_REF)
    if [[ $(git diff --name-only $BASE..$CI_BUILD_REF  -- '*.py' | wc -l) > 0 ]]; then
    docker-compose -p $CI_COMMIT_SHA up --exit-code-from flake8  --build flake8;
    fi
