variables:
  CONTAINER_IMAGE: dimavitvickiy/news_maker

build-image:
  stage: build
  tags:
  -  docker-vulyk-executor
  only:
  - master
  script:
  - docker build --build-arg VERSION=$CI_COMMIT_SHA -t $CONTAINER_IMAGE:$CI_COMMIT_SHA -f config/development/Dockerfile .
  - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA

stages:
  - build
  - test
  - deploy
  - lint

lint-python:
  stage: lint
  except:
  - master
  script:
  - |
    BASE=$(git merge-base origin/master $CI_BUILD_REF)
    if [[ $(git diff --name-only $BASE..$CI_BUILD_REF  -- '*.py' | wc -l) > 0 ]]; then
    docker-compose -p $CI_COMMIT_SHA up --exit-code-from flake8  --build flake8;
    fi
