stages:
  - build
  - test
  - deploy
  - lint

before_script:
-RUN apk --update add 'py-pip==8.1.2-r0' && \
  pip install 'docker-compose==1.8.0'

lint-python:
  stage: lint
  except:
  - master
  script:
  - |
    BASE=$(git merge-base origin/master $CI_BUILD_REF)
    if [[ $(git diff --name-only $BASE..$CI_BUILD_REF  -- '*.py' | wc -l) > 0 ]]; then
    docker-compose -p $CI_COMMIT_SHA up --exit-code-from flake8  --build flake8;
    fi
