version: "3"

services:
  server:
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    image: newsmaker-server
    command: ["watchexec", "-e", "py", "-r",  "python", "manage.py"]
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  flake8:
    image: newsmaker-server
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    entrypoint: ["flake8", "--config=flake8.cfg"]

networks:
  default:
    external:
      name: newsmaker
