version: "3"
services:
  server:
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    image: newsmaker-server
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  flake8:
    image: newsmaker-server
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    entrypoint: ["flake8", "--config=flake8.cfg"]
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - "/home/docker/data:/data"
    command: redis-server --appendonly yes
    networks:
    - webnet
networks:
  webnet:
