version: "3"

services:
  server:
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    image: newsmaker-server
    command: ["python","manage.py", "runserver"]
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - CONFIG_FILE=config/development/config.yml
    ports:
      - "5000:5000"
  flake8:
    image: newsmaker-server
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    entrypoint: ["flake8", "--config=flake8.cfg"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: news_maker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_maker_dev
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: newsmaker
