version: "3"

services:
  server:
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    image: newsmaker-server
    command: ["python","manage.py", "runserver"]
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - CONFIG_FILE=config/development/config.yml
    ports:
      - "5000:5000"
  flake8:
    image: newsmaker-server
    build:
      context: .
      dockerfile: config/development/Dockerfile.server
    entrypoint: ["flake8", "--config=flake8.cfg"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: news_maker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_maker_dev
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-init:
    image: newsmaker-server
    entrypoint: ["python", "manage.py", "db", "init"]
    environment:
      - CONFIG_FILE=config/development/config.yml
    volumes:
      - .:/app
  db-migrate:
    image: newsmaker-server
    entrypoint: ["python", "manage.py", "db", "migrate", "--message"]
    environment:
      - CONFIG_FILE=config/development/config.yml
    volumes:
      - .:/app
  db-upgrade:
    image: newsmaker-server
    entrypoint: ["python", "manage.py", "db", "upgrade"]
    environment:
      - CONFIG_FILE=config/development/config.yml
    volumes:
      - .:/app
  db-downgrade:
    image: newsmaker-server
    entrypoint: ["python", "manage.py", "db", "downgrade"]
    environment:
      - CONFIG_FILE=config/development/config.yml
    volumes:
      - .:/app


networks:
  default:
    external:
      name: newsmaker
