export const SET_COLOR_THEME = 'SET_COLOR_THEME'

export const CLEAR_TOKEN = 'CLEAR_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'

export const SET_ARTICLES = 'SET_ARTICLES';
export const ADD_ARTICLES = 'ADD_ARTICLES';
export const UPDATE_ARTICLES = 'UPDATE_ARTICLES';
export const REMOVE_ARTICLES = 'REMOVE_ARTICLES';


export const SET_CIRCLE_LOADER_VISIBILITY = 'SET_CIRCLE_LOADER_VISIBILITY';
export const SET_TRANSITION_LOADER_VISIBILITY = 'SET_TRANSITION_LOADER_VISIBILITY';
