// COLOR SWITCH
export const SET_COLOR_THEME = 'SET_COLOR_THEME'

// USER
export const CLEAR_TOKEN = 'CLEAR_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'


// ARTICLES
export const SET_ARTICLES = 'SET_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_CURRENT_ARTICLE_ID = 'UPDATE_CURRENT_ARTICLE_ID';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';


// TAGS
export const SET_TAGS = 'SET_TAGS';
export const ADD_TAG = 'ADD_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
// export const UPDATE_CURRENT_TAG_ID = 'UPDATE_CURRENT_TAG_ID';
export const REMOVE_TAG = 'REMOVE_TAG';


// RUBRICS
export const SET_RUBRICS = 'SET_RUBRICS';
export const ADD_RUBRIC = 'ADD_RUBRIC';
export const UPDATE_RUBRIC = 'UPDATE_RUBRIC';
// export const UPDATE_CURRENT_RUBRIC_ID = 'UPDATE_CURRENT_RUBRIC_ID';
export const REMOVE_RUBRIC = 'REMOVE_RUBRIC';


// UI
export const SET_CIRCLE_LOADER_VISIBILITY = 'SET_CIRCLE_LOADER_VISIBILITY';
export const SET_TRANSITION_LOADER_VISIBILITY = 'SET_TRANSITION_LOADER_VISIBILITY';
