export const SET_COLOR_THEME = 'SET_COLOR_THEME'

export const CLEAR_TOKEN = 'CLEAR_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'

export const SET_NEWS = 'SET_NEWS';
export const ADD_NEWS = 'ADD_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const REMOVE_NEWS = 'REMOVE_NEWS';


export const SET_CIRCLE_LOADER_VISIBILITY = 'SET_CIRCLE_LOADER_VISIBILITY';
export const SET_TRANSITION_LOADER_VISIBILITY = 'SET_TRANSITION_LOADER_VISIBILITY';
