FROM python:3.7.0

ARG DEBIAN_FRONTEND=noninteractive

RUN wget "https://github.com/watchexec/watchexec/releases/download/1.9.2/watchexec-1.9.2-x86_64-unknown-linux-gnu.deb"
RUN dpkg -i watchexec-1.9.2-x86_64-unknown-linux-gnu.deb
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install python-dev git python3-pkg-resources -y
RUN apt install flake8 -y

ADD requirements.txt /app/

WORKDIR /app

RUN python -m pip install -r requirements.txt

ADD . /app
